export const FETCH_BOOKS = "FETCH_BOOKS";
export const FETCH_BOOKS_SUCCEEDED = "FETCH_BOOKS_SUCCEEDED";
export const FETCH_BOOKS_FAILED = "FETCH_BOOKS_FAILED";
export const RESET_BOOKS = "RESET_BOOKS";
export const FETCH_BOOK_DETAIL = "FETCH_BOOK_DETAIL";
export const FETCH_BOOK_DETAIL_SUCCEEDED = "FETCH_BOOK_DETAIL_SUCCEEDED";
export const FETCH_BOOK_DETAIL_FAILED = "FETCH_BOOK_DETAIL_FAILED";
export const RESET_BOOK_DETAIL = "RESET_BOOK_DETAIL";
